# Generated by Django 5.2.4 on 2025-07-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('rating', models.FloatField()),
                ('poster1', models.ImageField(default='fallback.jpg', upload_to='')),
                ('poster2', models.ImageField(default='fallback.jpg', upload_to='')),
            ],
        ),
    ]
